---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7
    run_list:
      - recipe[yum-epel]
  - name: centos-7.2
    run_list:
      - recipe[yum-epel]

roles_path: test/integration/roles/

suites:
  - name: bareos-aio-server
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        client:
          sensitive_configs: false
        storage:
          sensitive_configs: false
          autochanger_enabled: true
        director:
          sensitive_configs: false
          conf:
            help:
              test: '# Some String'
        workstation:
          sensitive_configs: false
        plugins:
          graphite:
            cron_job: true
            sensitive_configs: false
