---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.14.89"

platforms:
  - name: debian-7.8
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    driver_config:
      # box_version 2.3.0 is bugged
      box_version: 2.2.9
    run_list:
      - recipe[apt]
  - name: centos-6.8
    driver_config:
      # box_version 2.3.0 is bugged
      box_version: 2.2.9
    run_list:
      - recipe[yum-epel]
  - name: centos-7.2
    driver_config:
      # box_version 2.3.0 is bugged
      box_version: 2.2.9
    run_list:
      - recipe[yum-epel]

suites:
  - name: bareos-aio-server
    run_list:
      - role[bareos_director]
    attributes:
      bareos:
        test_mode: true
        client:
          sensitive_configs: false
        storage:
          sensitive_configs: false
          autochanger_enabled: true
        director:
          sensitive_configs: false
          conf:
            help:
              test: '# Some String'
        workstation:
          sensitive_configs: false
        plugins:
          graphite:
            cron_job: true
            sensitive_configs: false
